name = "bluett-ericdy"
main = "src/index.ts"
compatibility_date = "2026-05-25"

[observability]
enabled = true

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "blt-bucket"

[vars]
PUBLIC_BASE_URL = "https://pub-969a2af2412a49999666d27f7d21bda1.r2.dev"
